// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahznwtpjpihrjvldaswh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoem53dHBqcGlocmp2bGRhc3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjU0MzAsImV4cCI6MjA1Njk0MTQzMH0.XVouVL0lvkNXMAHVrl3oqyG93K27INvlNYy0ZGDH0ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);